# Generated by Django 4.1.5 on 2024-08-05 13:49

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_alter_profile_cover_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default/blank.png', upload_to=back.models.user_cover_image_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(default='default/defaultprofile.jpg', upload_to=back.models.user_image_directory_path),
        ),
    ]
